import 'package:timetable/features/route_result/domain/entities/route_plan.dart';

const testRoute = RoutePlan(
  from: 'Bogor',
  to: 'Tangerang',
  travelTime: 134,
  fare: 10000,
  unitFare: 10000,
  currency: 'IDR',
  passengerCount: 1,
  stops: 31,
  serviceInfo: 'Layanan normal',
  hasTransit: true,
  transferCount: 1,
  preference: RoutePreference.fastest,
  steps: [
    RoutePlanStep(
      text: 'Naik dari Bogor',
      durationText: '0 menit',
      detailNote: 'KRL Lin Bogor',
      icon: 'train',
      color: '#E53935',
      isHeader: true,
      isTransit: false,
      isDestination: false,
    ),
    RoutePlanStep(
      text: 'Transit di Duri',
      durationText: '5 menit',
      detailNote: 'Pindah ke KRL Lin Tangerang',
      icon: 'directions_walk',
      color: '#8E44AD',
      isHeader: false,
      isTransit: true,
      isDestination: false,
    ),
    RoutePlanStep(
      text: 'Tiba di Tangerang',
      durationText: '134 menit',
      detailNote: 'Tujuan',
      icon: 'place',
      color: '#DC2626',
      isHeader: false,
      isTransit: false,
      isDestination: true,
    ),
  ],
  stationSequence: [],
  exitGateA: 'Pintu utama',
  exitGateB: 'Area antar-jemput',
);
