import 'package:timetable/features/route_result/domain/entities/route_plan.dart';

const testRoute = RoutePlan(
  from: 'Bogor',
  to: 'Tangerang',
  travelTime: 134,
  fare: 10000,
  unitFare: 10000,
  currency: 'IDR',
  passengerCount: 1,
  stops: 31,
  serviceInfo: 'Layanan normal',
  hasTransit: true,
  transferCount: 1,
  preference: RoutePreference.fastest,
  steps: [
    RoutePlanStep(
      kind: RouteStepKind.board,
      isWalking: false,
      text: 'Naik dari Bogor',
      durationText: '105 menit',
      detailNote: 'KRL Lin Bogor menuju Duri',
      icon: 'train',
      color: '#E53935',
      isHeader: true,
      isTransit: false,
      isDestination: false,
    ),
    RoutePlanStep(
      kind: RouteStepKind.transfer,
      isWalking: false,
      text: 'Pindah peron di Duri',
      durationText: '5 menit',
      detailNote: 'Pindah ke KRL Lin Tangerang',
      icon: 'sync_alt',
      color: '#8E44AD',
      isHeader: false,
      isTransit: true,
      isDestination: false,
    ),
    RoutePlanStep(
      kind: RouteStepKind.continueTrip,
      isWalking: false,
      text: 'Lanjut naik KRL Lin Tangerang',
      durationText: '24 menit',
      detailNote: 'Dari Duri menuju Tangerang',
      icon: 'train',
      color: '#8E44AD',
      isHeader: false,
      isTransit: false,
      isDestination: false,
    ),
    RoutePlanStep(
      kind: RouteStepKind.arrive,
      isWalking: false,
      text: 'Tiba di Tangerang',
      durationText: '134 menit',
      detailNote: 'Tujuan',
      icon: 'place',
      color: '#DC2626',
      isHeader: false,
      isTransit: false,
      isDestination: true,
    ),
  ],
  stationSequence: [
    RouteStation(
      stationId: 'bogor',
      name: 'Bogor',
      line: RouteLine(
        id: 'line-bogor',
        slug: 'bogor',
        name: 'Lin Bogor',
        color: '#E53935',
        serviceType: 'KRL',
      ),
    ),
    RouteStation(
      stationId: 'tangerang',
      name: 'Tangerang',
      line: RouteLine(
        id: 'line-tangerang',
        slug: 'tangerang',
        name: 'Lin Tangerang',
        color: '#8E44AD',
        serviceType: 'KRL',
      ),
    ),
  ],
  exitGateA: 'Pintu utama',
  exitGateB: 'Area antar-jemput',
);

const testWalkingRoute = RoutePlan(
  from: 'Cikoko',
  to: 'Tebet',
  travelTime: 9,
  fare: 5000,
  unitFare: 5000,
  currency: 'IDR',
  passengerCount: 1,
  stops: 2,
  serviceInfo: 'Layanan normal',
  hasTransit: true,
  transferCount: 1,
  preference: RoutePreference.fastest,
  steps: [
    RoutePlanStep(
      kind: RouteStepKind.board,
      isWalking: false,
      text: 'Naik dari Cikoko',
      durationText: '0 menit',
      detailNote: 'LRT Jabodebek Lin Bekasi menuju Cikoko',
      icon: 'train',
      color: '#00843D',
      isHeader: true,
      isTransit: false,
      isDestination: false,
    ),
    RoutePlanStep(
      kind: RouteStepKind.transfer,
      isWalking: true,
      text: 'Berjalan dari Cikoko menuju Stasiun Cawang',
      durationText: '5 menit',
      detailNote: 'Pindah ke KRL Lin Bogor',
      icon: 'directions_walk',
      color: '#E53935',
      isHeader: false,
      isTransit: true,
      isDestination: false,
    ),
    RoutePlanStep(
      kind: RouteStepKind.continueTrip,
      isWalking: false,
      text: 'Lanjut naik KRL Lin Bogor',
      durationText: '4 menit',
      detailNote: 'Dari Cawang menuju Tebet',
      icon: 'train',
      color: '#E53935',
      isHeader: false,
      isTransit: false,
      isDestination: false,
    ),
    RoutePlanStep(
      kind: RouteStepKind.arrive,
      isWalking: false,
      text: 'Tiba di Tebet',
      durationText: '9 menit',
      detailNote: 'Tujuan',
      icon: 'place',
      color: '#DC2626',
      isHeader: false,
      isTransit: false,
      isDestination: true,
    ),
  ],
  stationSequence: [],
  exitGateA: 'Pintu utama',
  exitGateB: 'Area antar-jemput',
);
